name: 'Terraform'

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'us-east-1'

    - name: Terraform Init
      run: terraform init
      working-directory: eks

    - name: Terraform Validate
      run: terraform validate
      working-directory: eks

    - name: Terraform Fmt
      run: terraform fmt
      working-directory: eks

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: eks

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
          
    - name: Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        quiet: true
        output_format: github_failed_only
        directory: eks
        framework: terraform 
      continue-on-error: true

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: eks

